# Site de pacotes de terceiros do python : https://pypi.org/

# Para instalar qualquer pacote : python -m pip install nome da biblioteca
# Para desinstalar qualquer pacote : python -m pip uninstall nome da biblioteca

# Tudo que estivar entre aspas é o que deves escrever no terminal (cmd) !!

# Para actualizar o pip digite isso no terminal : python.exe -m pip install --upgrade pip
# Para verificar a versão do pip , digite isso no terminal : python -m pip --version                                          Ou
# Para verificar a versão do pip , digite isso no terminal : py -m pip --version


# 1º passo : Abrir o terminal do windows (cmd) ou o terminal do python
# Dentro dele escreva "py" ou "python" da espaço e depois escreva "--version" e dá enter
# Escreva só os que estão dentro das aspas
# Isso te mostrará a versão do python instalado na sua máquina

# 2º passo :  Para saber quais pacotes tenho instalado no computador . usa-se o seguinte comando :
# Escreva : "py" ou "python" espaço "-m" espaço "pip" espaço "list"

# Para aceder as informações de um pacote : python -m pip show nome do pacote