# As string são conjunto de caracteres escritos numa sequência, uma vez criadas as strings não se pode alterar.
# Pode alterar-se o conteúdo dentro da variavel, mas não a string.

nome_1 = "Basílio"
letra_1 = nome_1[2]
print(letra_1)

# O len é uma função que usa-se pra mostrar e retornar a quantidade de caracteres que estão presentes na string:
print(len(nome_1))

# para concatenar duas strings usa-se o operador +
canal = "darkplay_channel"
you_tuber = "Basílio"
print(canal +"com"+ you_tuber)