numero_1 = 32 ; numero_2 = 2
print(numero_1 + numero_2)
print(numero_1 - numero_2)
print(numero_1 * numero_2)
print(numero_2 - numero_1)
print(numero_1 / numero_2)
print(numero_1 // numero_2)
print(numero_1 ** numero_2)
print(numero_2 ** numero_1)
print(numero_2 // numero_1)
print(numero_1 % numero_2)
print(numero_2 % numero_1)

# Ordem de precedência do operadores:
# 1º Parênteses
# 2º Potenciação
# 3º Multiplicação ou Divisão
# 4º Soma ou Subtração
# Esquerda para direita

# Exemplo aplicável :
print((numero_1 + numero_2) * numero_2)

# Casting é a conversão de tipo de dados

Username = str(input("What's your name ? "))
print("Hi",Username)