idade = 18 ; altura = 1.68

resultado = (idade >= 18) and (altura >= 1.60)
mensagem = "Pode aproximar-se ? " +str(resultado)
print(mensagem)

coracao = "Abertos" ; olhos = "Abertos"
resposta = (coracao == "Aberto") or (olhos == "Abertos")
Alerta = "Pode aproximar-se " +str(resposta)
print(Alerta)

tem_dinheiro = False ; tem_dinheiro = not tem_dinheiro

sim_ou_nao = "Tem dinheiro ? " +str(tem_dinheiro)
print(sim_ou_nao)