# O uso de operadores relacionasi ou operadores de comparação é focado em fazer comparação
# entre dois ou mais tipos de dados , e tem como saída valores logicos (True / False)

valor_1 = 37 ; valor_2 = 10
print(valor_1 == valor_2)
print(valor_1 > valor_2)
print(valor_1 < valor_2)
print(valor_2 > valor_1)
print(valor_2 < valor_1)
print(valor_1 != valor_2)
print(valor_1 >= valor_2)
print(valor_1 <= valor_2)
print(valor_2 <= valor_1)
print(valor_2 >= valor_1)